---
title: Scope and Method of Digital Music Research
author: Fabian C. Moss
date: 2022-08-14
---

Since October 2022, I am an Assistant Professor^["Juniorprofessor", as it's called in Germany.] for "Digital Music Philology and Music Theory" at [Ludwig-Maximilians-Universität, Würzburg](https://www.uni-wuerzburg.de/). I am writing this post to explain how I understand the denomination of this professorship, and how I want to fill it with life in research and teaching.
I find that this denomination actually well expresses my main research foci, but also that it might sound somewhat cryptic to non-specialists. Moreover, its constituent parts each can potentially have very diverging interpretations and meanings. In what follows I will present my personal understanding of this denomination, render explanations for it, and outline how I will fill it with life.

## Music Philology

Music philology is the science^[In anglophone contexts, "science" is usually restricted to the 'hard'/natural/formal sciences. In German, however, it applies to any form of academic research and processes of creating knowledge. I am not a big fan of the science-humanities dichotomie because there are too many points of overlap or unclear boundaries to justify this strict separation.] of musical texts. "Texts" should here be understood in the widest possible sense as "anything that can be read" - be it by a human reader or a computer. Examples of such texts are sheet music, sketches, letters, but also recordings, videos, and discourse about music, e.g. in historical books or on social media platforms. While philology is a very old academic discipline, it is highly relevant in our age, where information (often textual) plays a center stage role. 

On the other hand, not all music can be captured textually. The majority of cultures on our planet do not possess explicit writing systems for music, but nonetheless posses intricate forms of musical expression.
Studying these faces the challenge that philoligical methods seem non-applicable. While it is certainly possible to convert any form of music to a textual representation it is questionable whether these transcriptions are truthful representations of the music in the first place, and great care has to be taken not to introduce implicit biases.

## Music Theory

In the widest sense, music theory is the academic engagement with structures in music. Commonly, these encompass concepts like melody, rhythm, harmony, and form. 
While a definition of "music" is certainly problematic, most definitions contain at least some reference to structure, be it in the symbolic or in the sound domain. In my understanding, music theory should be a "Theory of Structures in Music". This wide concept enables the research community to look for commonalities (and differences!) between different forms of music around the globe and in different historical time periods.

## Digital

The denomination of my professorship is prepended with the qualifier "digital".
My understanding is that it equally applies to music philology and music theory. Thus, it expresses that my research and teaching activities draw on digital methods, study music in digital formats, or involve digitization/digitalization^[I differentiate "digitization" from "digitalization" in that the former means converting an analogue object (e.g. a sheet of paper) into a computer-representable form (e.g. a scan, or digital photo), whereas the latter means that this digital representation must also be represented in a structured computer-readable format (e.g. in some markup language or symbolic encoding)] 
of musical material.

Music research is in that sense always data-driven: historians draw on archives and historical documents, music psychologists design and conduct experiments to gather participant data, music theorists study many scores to attain a deeper understanding of structural relations therein, and ethnomusicologists aim for a deep understanding of a musical culture by closely engaging with its practices and recording (digitally, on tape, paper or in their own minds) certain musical expressions.

In my own research, I strongly draw on digital represetations of musical scores across a large historical range. This area is often called Corpus Studies.
It also feeds into formal modeling of music, that is, the questions how musical structures can be consistently described and related with one another.
This, in turn, allows in a final step to encage with "computational modeling" that aims at explaining musical concepts by using formal models and drawing on digital data.

```{mermaid}
flowchart LR
    A(Sources) --> B(Digitization/Digitalization)
    B --> C(Philology)
    C --> D(Theory)
    D --> B
```

## Conclusion

Modern digital music research is an exciting endeavour. 
It opens up completely new avenues of engaging with and obtaining a deeper understandig of music in all its diverse forms.
But this comes with the price of requiring to learn a host of new methods and techniques. Those are, most of the time, not only applicable to music and thus endow one with a deeper understanding of many other phenomena, and enable one to engage with research literatures from many fields such as digital humanities, cultural evolution, or computational sociology. 
We're just beginning to explore the vast oceans of opportunities for digital music research, and I count myself lucky to be at the forefront of this development!